export const HOME = '/'
export const LOGIN = '/login'
export const CHOOSE_PIZZA_FLAVOURS = '/escolher-sabor'
export const CHOOSE_PIZZA_QUANTITY = '/escolher-quantidade'
export const CHECKOUT = '/checkout'
